name: Security Pipeline

on:
  pull_request:
    branches: ["**"]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: security-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  security-scan:
    uses: jvrajunior/appsec-pipeline/.github/workflows/appsec-pipeline.yml@master
    secrets: inherit
    with:
      mobile: false
